// file type ini untuk menghindari type yang nantinya file ini akan diimport di file action atau reducer

// auth_types
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOGOUT = 'LOGOUT'

// animal_types
export const ADD_ANIMAL = 'ADD_ANIMAL';
export const ADD_ANIMAL_SUCCESS = 'ADD_ANIMAL_SUCCESS';
export const ADD_ANIMAL_FAILED = 'ADD_ANIMAL_FAILED';

export const GET_ANIMAL = 'GET_ANIMAL';
export const GET_ANIMAL_SUCCESS = 'GET_ANIMAL_SUCCESS';
export const GET_ANIMAL_FAILED = 'GET_ANIMAL_FAILED';

export const DELETE_ANIMAL = 'DELETE_ANIMAL';
export const DELETE_ANIMAL_SUCCESS = 'DELETE_ANIMAL_SUCCESS';
export const DELETE_ANIMAL_FAILED = 'DELETE_ANIMAL_FAILED';

// booking_types
export const BOOKING = 'BOOKING';
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS';
export const BOOKING_FAILED = 'BOOKING_FAILED';

export const GET_BOOKING = 'GET_BOOKING';
export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS';
export const GET_BOOKING_FAILED = 'GET_BOOKING_FAILED';

export const GET_HISTORY_BOOKING = 'GET_HISTORY_BOOKING';
export const GET_HISTORY_BOOKING_SUCCESS = 'GET_HISTORY_BOOKING_SUCCESS';
export const GET_HISTORY_BOOKING_FAILED = 'GET_HISTORY_BOOKING_FAILED';

// clinic_types
export const REQUEST_GET_CLINIC = 'REQUEST_GET_CLINIC'
export const GET_CLINIC = 'GET_CLINIC';
export const GET_CLINIC_SUCCESS = 'GET_CLINIC_SUCCESS';
export const GET_CLINIC_FAILED = 'GET_CLINIC_FAILED';

export const GET_CLINIC_SEARCH = 'GET_CLINIC_SEARCH';
export const GET_CLINIC_SUCCESS_SEARCH = 'GET_CLINIC_SUCCES_SEARCH';
export const GET_CLINIC_FAILED_SEARCH = 'GET_CLINIC_FAILED_SEARCH';

export const GET_CLINIC_CITY = 'GET_CLINIC_CITY';
export const GET_CLINIC_SUCCESS_CITY = 'GET_CLINIC_SUCCES_CITY';
export const GET_CLINIC_FAILED_CITY = 'GET_CLINIC_FAILED_CITY';

export const GET_CLINIC_PET = 'GET_CLINIC_PET';
export const GET_CLINIC_SUCCESS_PET = 'GET_CLINIC_SUCCES_PET';
export const GET_CLINIC_FAILED_PET = 'GET_CLINIC_FAILED_PET';

// clinivDetail_types
export const GET_CLINIC_DETAIL = 'GET_CLINIC_DETAIL';
export const GET_CLINIC_DETAIL_SUCCESS = 'GET_CLINIC_DETAIL_SUCCESS';
export const GET_CLINIC_DETAIL_FAILED = 'GET_CLINIC_DETAIL_FAILED';


// profile_types
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
